### ISSUE TITLE
Consultation about Open Source Code

### ISSUE THREAD

**Issue by cyfedu-dlut** [Wayne-Mai/EgoLoc#1]
Hello, there is no doubt that this is a great and meaningful job. I would like to inquire about the open source time of the complete code, which is very valuable and helpful for me to understand your work. Thanks again, I am very sorry for the disturbance. I look forward to your reply.

**Comment by Wayne-Mai** [comment]
@cyfedu-dlut   Thanks for your attention. Sorry I was busy with other issues before. Now almost the whole project is published. You should be able to reproduce our results in the paper now.

**Comment by cyfedu-dlut** [comment]
thanks a lot！best wishes for you！



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/09/2024 02:59 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Wayne-Mai/EgoLoc] Consultation about Open Source Code (Issue #1) |

Closed #1 as completed.
