### ISSUE TITLE
Related to open-source problem

### ISSUE THREAD

**Issue by EgoAlpha** [Wayne-Mai/EgoLoc#2]
Hello, no doubt this is a great work, I have a question for you about the time of open sourcing the complete project, much looking forward for you to open source the whole project completely as soon as possible, thanks again! Best wishes for you！！！

**Comment by Wayne-Mai** [comment]
@EgoAlpha  Thanks for your attention. Sorry I was busy with other issues before. Now almost the whole project is published. You should be able to reproduce our results in the paper now.
